# Generated by Django 4.1.1 on 2022-10-19 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_remove_shippingaddress_order_orderitem_address_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderitem",
            name="address",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="city",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="country",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="postalCode",
        ),
        migrations.AddField(
            model_name="order",
            name="address",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="city",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="country",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="postalCode",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
