# Generated by Django 4.1.1 on 2022-10-12 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0004_alter_product_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="hidden",
            field=models.BooleanField(default=False),
        ),
    ]
